/* 
 * Betaface API 2.0
 *
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAdminApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// get API usage information. (Administrative endpoint - API secret required)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">your API key or d45fd466-51e2-4701-8da8-04351c872236</param>
        /// <param name="apiSecret">your API secret. It is not recommended to expose your application secret at client side.</param>
        /// <returns>Usage</returns>
        Usage V2AdminUsageGet (Guid? apiKey, Guid? apiSecret);

        /// <summary>
        /// get API usage information. (Administrative endpoint - API secret required)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">your API key or d45fd466-51e2-4701-8da8-04351c872236</param>
        /// <param name="apiSecret">your API secret. It is not recommended to expose your application secret at client side.</param>
        /// <returns>ApiResponse of Usage</returns>
        ApiResponse<Usage> V2AdminUsageGetWithHttpInfo (Guid? apiKey, Guid? apiSecret);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// get API usage information. (Administrative endpoint - API secret required)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">your API key or d45fd466-51e2-4701-8da8-04351c872236</param>
        /// <param name="apiSecret">your API secret. It is not recommended to expose your application secret at client side.</param>
        /// <returns>Task of Usage</returns>
        System.Threading.Tasks.Task<Usage> V2AdminUsageGetAsync (Guid? apiKey, Guid? apiSecret);

        /// <summary>
        /// get API usage information. (Administrative endpoint - API secret required)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">your API key or d45fd466-51e2-4701-8da8-04351c872236</param>
        /// <param name="apiSecret">your API secret. It is not recommended to expose your application secret at client side.</param>
        /// <returns>Task of ApiResponse (Usage)</returns>
        System.Threading.Tasks.Task<ApiResponse<Usage>> V2AdminUsageGetAsyncWithHttpInfo (Guid? apiKey, Guid? apiSecret);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AdminApi : IAdminApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AdminApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AdminApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AdminApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AdminApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// get API usage information. (Administrative endpoint - API secret required) 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">your API key or d45fd466-51e2-4701-8da8-04351c872236</param>
        /// <param name="apiSecret">your API secret. It is not recommended to expose your application secret at client side.</param>
        /// <returns>Usage</returns>
        public Usage V2AdminUsageGet (Guid? apiKey, Guid? apiSecret)
        {
             ApiResponse<Usage> localVarResponse = V2AdminUsageGetWithHttpInfo(apiKey, apiSecret);
             return localVarResponse.Data;
        }

        /// <summary>
        /// get API usage information. (Administrative endpoint - API secret required) 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">your API key or d45fd466-51e2-4701-8da8-04351c872236</param>
        /// <param name="apiSecret">your API secret. It is not recommended to expose your application secret at client side.</param>
        /// <returns>ApiResponse of Usage</returns>
        public ApiResponse< Usage > V2AdminUsageGetWithHttpInfo (Guid? apiKey, Guid? apiSecret)
        {
            // verify the required parameter 'apiKey' is set
            if (apiKey == null)
                throw new ApiException(400, "Missing required parameter 'apiKey' when calling AdminApi->V2AdminUsageGet");
            // verify the required parameter 'apiSecret' is set
            if (apiSecret == null)
                throw new ApiException(400, "Missing required parameter 'apiSecret' when calling AdminApi->V2AdminUsageGet");

            var localVarPath = "/v2/admin/usage";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apiKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "api_key", apiKey)); // query parameter
            if (apiSecret != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "api_secret", apiSecret)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V2AdminUsageGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Usage>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Usage) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Usage)));
        }

        /// <summary>
        /// get API usage information. (Administrative endpoint - API secret required) 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">your API key or d45fd466-51e2-4701-8da8-04351c872236</param>
        /// <param name="apiSecret">your API secret. It is not recommended to expose your application secret at client side.</param>
        /// <returns>Task of Usage</returns>
        public async System.Threading.Tasks.Task<Usage> V2AdminUsageGetAsync (Guid? apiKey, Guid? apiSecret)
        {
             ApiResponse<Usage> localVarResponse = await V2AdminUsageGetAsyncWithHttpInfo(apiKey, apiSecret);
             return localVarResponse.Data;

        }

        /// <summary>
        /// get API usage information. (Administrative endpoint - API secret required) 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">your API key or d45fd466-51e2-4701-8da8-04351c872236</param>
        /// <param name="apiSecret">your API secret. It is not recommended to expose your application secret at client side.</param>
        /// <returns>Task of ApiResponse (Usage)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Usage>> V2AdminUsageGetAsyncWithHttpInfo (Guid? apiKey, Guid? apiSecret)
        {
            // verify the required parameter 'apiKey' is set
            if (apiKey == null)
                throw new ApiException(400, "Missing required parameter 'apiKey' when calling AdminApi->V2AdminUsageGet");
            // verify the required parameter 'apiSecret' is set
            if (apiSecret == null)
                throw new ApiException(400, "Missing required parameter 'apiSecret' when calling AdminApi->V2AdminUsageGet");

            var localVarPath = "/v2/admin/usage";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apiKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "api_key", apiKey)); // query parameter
            if (apiSecret != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "api_secret", apiSecret)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V2AdminUsageGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Usage>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Usage) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Usage)));
        }

    }
}
