/* 
 * Betaface API 2.0
 *
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPersonApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// lists all persons and their faces identifiers sorted by namespace and person name alphabetically. (Administrative endpoint - API secret required)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">your API key or d45fd466-51e2-4701-8da8-04351c872236</param>
        /// <param name="apiSecret">your API secret. It is not recommended to expose your application secret at client side.</param>
        /// <param name="personId">(optional) query parameters array of specific person ids or all@namespace to list persons in that namespace (optional)</param>
        /// <returns>List&lt;Person&gt;</returns>
        List<Person> V2PersonGet (Guid? apiKey, Guid? apiSecret, List<string> personId = null);

        /// <summary>
        /// lists all persons and their faces identifiers sorted by namespace and person name alphabetically. (Administrative endpoint - API secret required)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">your API key or d45fd466-51e2-4701-8da8-04351c872236</param>
        /// <param name="apiSecret">your API secret. It is not recommended to expose your application secret at client side.</param>
        /// <param name="personId">(optional) query parameters array of specific person ids or all@namespace to list persons in that namespace (optional)</param>
        /// <returns>ApiResponse of List&lt;Person&gt;</returns>
        ApiResponse<List<Person>> V2PersonGetWithHttpInfo (Guid? apiKey, Guid? apiSecret, List<string> personId = null);
        /// <summary>
        /// sets or overwrites person id for each specified face.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">request json body with parameters. (optional)</param>
        /// <returns></returns>
        void V2PersonPost (SetPerson body = null);

        /// <summary>
        /// sets or overwrites person id for each specified face.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">request json body with parameters. (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> V2PersonPostWithHttpInfo (SetPerson body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// lists all persons and their faces identifiers sorted by namespace and person name alphabetically. (Administrative endpoint - API secret required)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">your API key or d45fd466-51e2-4701-8da8-04351c872236</param>
        /// <param name="apiSecret">your API secret. It is not recommended to expose your application secret at client side.</param>
        /// <param name="personId">(optional) query parameters array of specific person ids or all@namespace to list persons in that namespace (optional)</param>
        /// <returns>Task of List&lt;Person&gt;</returns>
        System.Threading.Tasks.Task<List<Person>> V2PersonGetAsync (Guid? apiKey, Guid? apiSecret, List<string> personId = null);

        /// <summary>
        /// lists all persons and their faces identifiers sorted by namespace and person name alphabetically. (Administrative endpoint - API secret required)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">your API key or d45fd466-51e2-4701-8da8-04351c872236</param>
        /// <param name="apiSecret">your API secret. It is not recommended to expose your application secret at client side.</param>
        /// <param name="personId">(optional) query parameters array of specific person ids or all@namespace to list persons in that namespace (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;Person&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Person>>> V2PersonGetAsyncWithHttpInfo (Guid? apiKey, Guid? apiSecret, List<string> personId = null);
        /// <summary>
        /// sets or overwrites person id for each specified face.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">request json body with parameters. (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task V2PersonPostAsync (SetPerson body = null);

        /// <summary>
        /// sets or overwrites person id for each specified face.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">request json body with parameters. (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> V2PersonPostAsyncWithHttpInfo (SetPerson body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PersonApi : IPersonApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PersonApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PersonApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PersonApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PersonApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// lists all persons and their faces identifiers sorted by namespace and person name alphabetically. (Administrative endpoint - API secret required) 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">your API key or d45fd466-51e2-4701-8da8-04351c872236</param>
        /// <param name="apiSecret">your API secret. It is not recommended to expose your application secret at client side.</param>
        /// <param name="personId">(optional) query parameters array of specific person ids or all@namespace to list persons in that namespace (optional)</param>
        /// <returns>List&lt;Person&gt;</returns>
        public List<Person> V2PersonGet (Guid? apiKey, Guid? apiSecret, List<string> personId = null)
        {
             ApiResponse<List<Person>> localVarResponse = V2PersonGetWithHttpInfo(apiKey, apiSecret, personId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// lists all persons and their faces identifiers sorted by namespace and person name alphabetically. (Administrative endpoint - API secret required) 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">your API key or d45fd466-51e2-4701-8da8-04351c872236</param>
        /// <param name="apiSecret">your API secret. It is not recommended to expose your application secret at client side.</param>
        /// <param name="personId">(optional) query parameters array of specific person ids or all@namespace to list persons in that namespace (optional)</param>
        /// <returns>ApiResponse of List&lt;Person&gt;</returns>
        public ApiResponse< List<Person> > V2PersonGetWithHttpInfo (Guid? apiKey, Guid? apiSecret, List<string> personId = null)
        {
            // verify the required parameter 'apiKey' is set
            if (apiKey == null)
                throw new ApiException(400, "Missing required parameter 'apiKey' when calling PersonApi->V2PersonGet");
            // verify the required parameter 'apiSecret' is set
            if (apiSecret == null)
                throw new ApiException(400, "Missing required parameter 'apiSecret' when calling PersonApi->V2PersonGet");

            var localVarPath = "/v2/person";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apiKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "api_key", apiKey)); // query parameter
            if (apiSecret != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "api_secret", apiSecret)); // query parameter
            if (personId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "person_id", personId)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V2PersonGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Person>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<Person>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Person>)));
        }

        /// <summary>
        /// lists all persons and their faces identifiers sorted by namespace and person name alphabetically. (Administrative endpoint - API secret required) 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">your API key or d45fd466-51e2-4701-8da8-04351c872236</param>
        /// <param name="apiSecret">your API secret. It is not recommended to expose your application secret at client side.</param>
        /// <param name="personId">(optional) query parameters array of specific person ids or all@namespace to list persons in that namespace (optional)</param>
        /// <returns>Task of List&lt;Person&gt;</returns>
        public async System.Threading.Tasks.Task<List<Person>> V2PersonGetAsync (Guid? apiKey, Guid? apiSecret, List<string> personId = null)
        {
             ApiResponse<List<Person>> localVarResponse = await V2PersonGetAsyncWithHttpInfo(apiKey, apiSecret, personId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// lists all persons and their faces identifiers sorted by namespace and person name alphabetically. (Administrative endpoint - API secret required) 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">your API key or d45fd466-51e2-4701-8da8-04351c872236</param>
        /// <param name="apiSecret">your API secret. It is not recommended to expose your application secret at client side.</param>
        /// <param name="personId">(optional) query parameters array of specific person ids or all@namespace to list persons in that namespace (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;Person&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Person>>> V2PersonGetAsyncWithHttpInfo (Guid? apiKey, Guid? apiSecret, List<string> personId = null)
        {
            // verify the required parameter 'apiKey' is set
            if (apiKey == null)
                throw new ApiException(400, "Missing required parameter 'apiKey' when calling PersonApi->V2PersonGet");
            // verify the required parameter 'apiSecret' is set
            if (apiSecret == null)
                throw new ApiException(400, "Missing required parameter 'apiSecret' when calling PersonApi->V2PersonGet");

            var localVarPath = "/v2/person";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apiKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "api_key", apiKey)); // query parameter
            if (apiSecret != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "api_secret", apiSecret)); // query parameter
            if (personId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "person_id", personId)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V2PersonGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Person>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<Person>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Person>)));
        }

        /// <summary>
        /// sets or overwrites person id for each specified face. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">request json body with parameters. (optional)</param>
        /// <returns></returns>
        public void V2PersonPost (SetPerson body = null)
        {
             V2PersonPostWithHttpInfo(body);
        }

        /// <summary>
        /// sets or overwrites person id for each specified face. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">request json body with parameters. (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> V2PersonPostWithHttpInfo (SetPerson body = null)
        {

            var localVarPath = "/v2/person";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V2PersonPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// sets or overwrites person id for each specified face. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">request json body with parameters. (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task V2PersonPostAsync (SetPerson body = null)
        {
             await V2PersonPostAsyncWithHttpInfo(body);

        }

        /// <summary>
        /// sets or overwrites person id for each specified face. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">request json body with parameters. (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> V2PersonPostAsyncWithHttpInfo (SetPerson body = null)
        {

            var localVarPath = "/v2/person";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V2PersonPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

    }
}
