/* 
 * Betaface API 2.0
 *
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CroppedFace
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CroppedFaceTests
    {
        // TODO uncomment below to declare an instance variable for CroppedFace
        //private CroppedFace instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CroppedFace
            //instance = new CroppedFace();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CroppedFace
        /// </summary>
        [Test]
        public void CroppedFaceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CroppedFace
            //Assert.IsInstanceOfType<CroppedFace> (instance, "variable 'instance' is a CroppedFace");
        }


        /// <summary>
        /// Test the property 'ImageBase64'
        /// </summary>
        [Test]
        public void ImageBase64Test()
        {
            // TODO unit test for the property 'ImageBase64'
        }
        /// <summary>
        /// Test the property 'Face'
        /// </summary>
        [Test]
        public void FaceTest()
        {
            // TODO unit test for the property 'Face'
        }

    }

}
