/* 
 * Betaface API 2.0
 *
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Face
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FaceTests
    {
        // TODO uncomment below to declare an instance variable for Face
        //private Face instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Face
            //instance = new Face();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Face
        /// </summary>
        [Test]
        public void FaceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Face
            //Assert.IsInstanceOfType<Face> (instance, "variable 'instance' is a Face");
        }


        /// <summary>
        /// Test the property 'FaceUuid'
        /// </summary>
        [Test]
        public void FaceUuidTest()
        {
            // TODO unit test for the property 'FaceUuid'
        }
        /// <summary>
        /// Test the property 'MediaUuid'
        /// </summary>
        [Test]
        public void MediaUuidTest()
        {
            // TODO unit test for the property 'MediaUuid'
        }
        /// <summary>
        /// Test the property 'X'
        /// </summary>
        [Test]
        public void XTest()
        {
            // TODO unit test for the property 'X'
        }
        /// <summary>
        /// Test the property 'Y'
        /// </summary>
        [Test]
        public void YTest()
        {
            // TODO unit test for the property 'Y'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'Angle'
        /// </summary>
        [Test]
        public void AngleTest()
        {
            // TODO unit test for the property 'Angle'
        }
        /// <summary>
        /// Test the property 'DetectionScore'
        /// </summary>
        [Test]
        public void DetectionScoreTest()
        {
            // TODO unit test for the property 'DetectionScore'
        }
        /// <summary>
        /// Test the property 'Points'
        /// </summary>
        [Test]
        public void PointsTest()
        {
            // TODO unit test for the property 'Points'
        }
        /// <summary>
        /// Test the property 'UserPoints'
        /// </summary>
        [Test]
        public void UserPointsTest()
        {
            // TODO unit test for the property 'UserPoints'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'PersonId'
        /// </summary>
        [Test]
        public void PersonIdTest()
        {
            // TODO unit test for the property 'PersonId'
        }
        /// <summary>
        /// Test the property 'AppearanceId'
        /// </summary>
        [Test]
        public void AppearanceIdTest()
        {
            // TODO unit test for the property 'AppearanceId'
        }
        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Test]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }

    }

}
