/* 
 * Betaface API 2.0
 *
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Match
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MatchTests
    {
        // TODO uncomment below to declare an instance variable for Match
        //private Match instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Match
            //instance = new Match();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Match
        /// </summary>
        [Test]
        public void MatchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Match
            //Assert.IsInstanceOfType<Match> (instance, "variable 'instance' is a Match");
        }


        /// <summary>
        /// Test the property 'FaceUuid'
        /// </summary>
        [Test]
        public void FaceUuidTest()
        {
            // TODO unit test for the property 'FaceUuid'
        }
        /// <summary>
        /// Test the property 'Confidence'
        /// </summary>
        [Test]
        public void ConfidenceTest()
        {
            // TODO unit test for the property 'Confidence'
        }
        /// <summary>
        /// Test the property 'IsMatch'
        /// </summary>
        [Test]
        public void IsMatchTest()
        {
            // TODO unit test for the property 'IsMatch'
        }
        /// <summary>
        /// Test the property 'PersonId'
        /// </summary>
        [Test]
        public void PersonIdTest()
        {
            // TODO unit test for the property 'PersonId'
        }

    }

}
