/* 
 * Betaface API 2.0
 *
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Media
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MediaTests
    {
        // TODO uncomment below to declare an instance variable for Media
        //private Media instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Media
            //instance = new Media();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Media
        /// </summary>
        [Test]
        public void MediaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Media
            //Assert.IsInstanceOfType<Media> (instance, "variable 'instance' is a Media");
        }


        /// <summary>
        /// Test the property 'MediaUuid'
        /// </summary>
        [Test]
        public void MediaUuidTest()
        {
            // TODO unit test for the property 'MediaUuid'
        }
        /// <summary>
        /// Test the property 'Checksum'
        /// </summary>
        [Test]
        public void ChecksumTest()
        {
            // TODO unit test for the property 'Checksum'
        }
        /// <summary>
        /// Test the property 'Faces'
        /// </summary>
        [Test]
        public void FacesTest()
        {
            // TODO unit test for the property 'Faces'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'OriginalFilename'
        /// </summary>
        [Test]
        public void OriginalFilenameTest()
        {
            // TODO unit test for the property 'OriginalFilename'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }

    }

}
