/* 
 * Betaface API 2.0
 *
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MediaUpload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MediaUploadTests
    {
        // TODO uncomment below to declare an instance variable for MediaUpload
        //private MediaUpload instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MediaUpload
            //instance = new MediaUpload();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MediaUpload
        /// </summary>
        [Test]
        public void MediaUploadInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MediaUpload
            //Assert.IsInstanceOfType<MediaUpload> (instance, "variable 'instance' is a MediaUpload");
        }


        /// <summary>
        /// Test the property 'ApiKey'
        /// </summary>
        [Test]
        public void ApiKeyTest()
        {
            // TODO unit test for the property 'ApiKey'
        }
        /// <summary>
        /// Test the property 'FileUri'
        /// </summary>
        [Test]
        public void FileUriTest()
        {
            // TODO unit test for the property 'FileUri'
        }
        /// <summary>
        /// Test the property 'FileBase64'
        /// </summary>
        [Test]
        public void FileBase64Test()
        {
            // TODO unit test for the property 'FileBase64'
        }
        /// <summary>
        /// Test the property 'DetectionFlags'
        /// </summary>
        [Test]
        public void DetectionFlagsTest()
        {
            // TODO unit test for the property 'DetectionFlags'
        }
        /// <summary>
        /// Test the property 'DetectionMinScore'
        /// </summary>
        [Test]
        public void DetectionMinScoreTest()
        {
            // TODO unit test for the property 'DetectionMinScore'
        }
        /// <summary>
        /// Test the property 'DetectionNewFaces'
        /// </summary>
        [Test]
        public void DetectionNewFacesTest()
        {
            // TODO unit test for the property 'DetectionNewFaces'
        }
        /// <summary>
        /// Test the property 'SetPersonId'
        /// </summary>
        [Test]
        public void SetPersonIdTest()
        {
            // TODO unit test for the property 'SetPersonId'
        }
        /// <summary>
        /// Test the property 'RecognizeTargets'
        /// </summary>
        [Test]
        public void RecognizeTargetsTest()
        {
            // TODO unit test for the property 'RecognizeTargets'
        }
        /// <summary>
        /// Test the property 'RecognizeParameters'
        /// </summary>
        [Test]
        public void RecognizeParametersTest()
        {
            // TODO unit test for the property 'RecognizeParameters'
        }
        /// <summary>
        /// Test the property 'OriginalFilename'
        /// </summary>
        [Test]
        public void OriginalFilenameTest()
        {
            // TODO unit test for the property 'OriginalFilename'
        }

    }

}
