/* 
 * Betaface API 2.0
 *
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RecognizeResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RecognizeResultTests
    {
        // TODO uncomment below to declare an instance variable for RecognizeResult
        //private RecognizeResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RecognizeResult
            //instance = new RecognizeResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RecognizeResult
        /// </summary>
        [Test]
        public void RecognizeResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RecognizeResult
            //Assert.IsInstanceOfType<RecognizeResult> (instance, "variable 'instance' is a RecognizeResult");
        }


        /// <summary>
        /// Test the property 'FaceUuid'
        /// </summary>
        [Test]
        public void FaceUuidTest()
        {
            // TODO unit test for the property 'FaceUuid'
        }
        /// <summary>
        /// Test the property 'Matches'
        /// </summary>
        [Test]
        public void MatchesTest()
        {
            // TODO unit test for the property 'Matches'
        }

    }

}
