/* 
 * Betaface API 2.0
 *
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RecognizeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RecognizeRequestTests
    {
        // TODO uncomment below to declare an instance variable for RecognizeRequest
        //private RecognizeRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RecognizeRequest
            //instance = new RecognizeRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RecognizeRequest
        /// </summary>
        [Test]
        public void RecognizeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RecognizeRequest
            //Assert.IsInstanceOfType<RecognizeRequest> (instance, "variable 'instance' is a RecognizeRequest");
        }


        /// <summary>
        /// Test the property 'ApiKey'
        /// </summary>
        [Test]
        public void ApiKeyTest()
        {
            // TODO unit test for the property 'ApiKey'
        }
        /// <summary>
        /// Test the property 'FacesUuids'
        /// </summary>
        [Test]
        public void FacesUuidsTest()
        {
            // TODO unit test for the property 'FacesUuids'
        }
        /// <summary>
        /// Test the property 'Targets'
        /// </summary>
        [Test]
        public void TargetsTest()
        {
            // TODO unit test for the property 'Targets'
        }
        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Test]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }

    }

}
