/* 
 * Betaface API 2.0
 *
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Recognize
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RecognizeTests
    {
        // TODO uncomment below to declare an instance variable for Recognize
        //private Recognize instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Recognize
            //instance = new Recognize();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Recognize
        /// </summary>
        [Test]
        public void RecognizeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Recognize
            //Assert.IsInstanceOfType<Recognize> (instance, "variable 'instance' is a Recognize");
        }


        /// <summary>
        /// Test the property 'RecognizeUuid'
        /// </summary>
        [Test]
        public void RecognizeUuidTest()
        {
            // TODO unit test for the property 'RecognizeUuid'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Test]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

    }

}
