/* 
 * Betaface API 2.0
 *
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Usage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UsageTests
    {
        // TODO uncomment below to declare an instance variable for Usage
        //private Usage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Usage
            //instance = new Usage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Usage
        /// </summary>
        [Test]
        public void UsageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Usage
            //Assert.IsInstanceOfType<Usage> (instance, "variable 'instance' is a Usage");
        }


        /// <summary>
        /// Test the property 'UsageDaily'
        /// </summary>
        [Test]
        public void UsageDailyTest()
        {
            // TODO unit test for the property 'UsageDaily'
        }

    }

}
