/* 
 * Betaface API 2.0
 *
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MediaApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class MediaApiTests
    {
        private MediaApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new MediaApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MediaApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' MediaApi
            //Assert.IsInstanceOfType(typeof(MediaApi), instance, "instance is a MediaApi");
        }

        
        /// <summary>
        /// Test V2MediaFilePost
        /// </summary>
        [Test]
        public void V2MediaFilePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? apiKey = null;
            //System.IO.Stream _file = null;
            //string detectionFlags = null;
            //double? detectionMinScore = null;
            //string detectionNewFaces = null;
            //string setPersonId = null;
            //string recognizeTargets = null;
            //string recognizeParameters = null;
            //string originalFilename = null;
            //var response = instance.V2MediaFilePost(apiKey, _file, detectionFlags, detectionMinScore, detectionNewFaces, setPersonId, recognizeTargets, recognizeParameters, originalFilename);
            //Assert.IsInstanceOf<MediaUploadResponse> (response, "response is MediaUploadResponse");
        }
        
        /// <summary>
        /// Test V2MediaGet
        /// </summary>
        [Test]
        public void V2MediaGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? apiKey = null;
            //Guid? mediaUuid = null;
            //var response = instance.V2MediaGet(apiKey, mediaUuid);
            //Assert.IsInstanceOf<Media> (response, "response is Media");
        }
        
        /// <summary>
        /// Test V2MediaHashGet
        /// </summary>
        [Test]
        public void V2MediaHashGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? apiKey = null;
            //string checksum = null;
            //var response = instance.V2MediaHashGet(apiKey, checksum);
            //Assert.IsInstanceOf<Media> (response, "response is Media");
        }
        
        /// <summary>
        /// Test V2MediaPost
        /// </summary>
        [Test]
        public void V2MediaPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //MediaUpload body = null;
            //var response = instance.V2MediaPost(body);
            //Assert.IsInstanceOf<MediaUploadResponse> (response, "response is MediaUploadResponse");
        }
        
    }

}
