/* 
 * Betaface API 2.0
 *
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RecognizeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RecognizeApiTests
    {
        private RecognizeApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RecognizeApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RecognizeApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RecognizeApi
            //Assert.IsInstanceOfType(typeof(RecognizeApi), instance, "instance is a RecognizeApi");
        }

        
        /// <summary>
        /// Test V2RecognizeGet
        /// </summary>
        [Test]
        public void V2RecognizeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? apiKey = null;
            //Guid? recognizeUuid = null;
            //instance.V2RecognizeGet(apiKey, recognizeUuid);
            
        }
        
        /// <summary>
        /// Test V2RecognizePost
        /// </summary>
        [Test]
        public void V2RecognizePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RecognizeRequest body = null;
            //var response = instance.V2RecognizePost(body);
            //Assert.IsInstanceOf<Recognize> (response, "response is Recognize");
        }
        
    }

}
