/* 
 * Betaface API 2.0
 *
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// represents a media file upload message json body parameters.
    /// </summary>
    [DataContract]
    public partial class MediaUpload :  IEquatable<MediaUpload>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MediaUpload" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MediaUpload() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MediaUpload" /> class.
        /// </summary>
        /// <param name="apiKey">your API key or d45fd466-51e2-4701-8da8-04351c872236 (required).</param>
        /// <param name="fileUri">publicly accessible media file uri..</param>
        /// <param name="fileBase64">base64 encoded media file content. file_uri parameter will be ignored if file_base64 parameter is specified and not empty..</param>
        /// <param name="detectionFlags">(optional) comma separated list of detection flags: bestface - return only face with highest detection score, centerface - same as bestface but gives preference to face closest to image center, basicpoints - 22 basic points detection, propoints - 101 pro points detection, classifiers - face classification and attributes, extended - extended color and geometric measurements, content - image content detection.  for example: \&quot;basicpoints,propoints,classifiers,content\&quot;.</param>
        /// <param name="detectionMinScore">(optional) filter faces with detection score lower than min_score..</param>
        /// <param name="detectionNewFaces">(optional) override automatic faces detection and manually specify faces locations, face points and person ids to assign.  provide an array of new faces.</param>
        /// <param name="setPersonId">(optional) set person id in format name@namespace to each detected face. recommended to use with detection_flags bestface, centerface and/or min_score minimum detection score parameter..</param>
        /// <param name="recognizeTargets">(optional) for each detected face run recognize against specified targets (face ids, person ids or namespaces)..</param>
        /// <param name="recognizeParameters">(optional) comma separated list of recognition parameters, currently supported min_match_score (minimum recognition score), min_score (minimum detection score), gender and race filter.  for example: \&quot;min_match_score:0.4,min_score:0.2,gender:male,race:white\&quot;.</param>
        /// <param name="originalFilename">(optional) original media filename, path, uri or your application specific id that you want to be stored in media metadata for reference..</param>
        public MediaUpload(Guid? apiKey = default(Guid?), string fileUri = default(string), string fileBase64 = default(string), string detectionFlags = default(string), double? detectionMinScore = default(double?), List<NewFace> detectionNewFaces = default(List<NewFace>), string setPersonId = default(string), List<string> recognizeTargets = default(List<string>), string recognizeParameters = default(string), string originalFilename = default(string))
        {
            // to ensure "apiKey" is required (not null)
            if (apiKey == null)
            {
                throw new InvalidDataException("apiKey is a required property for MediaUpload and cannot be null");
            }
            else
            {
                this.ApiKey = apiKey;
            }
            this.FileUri = fileUri;
            this.FileBase64 = fileBase64;
            this.DetectionFlags = detectionFlags;
            this.DetectionMinScore = detectionMinScore;
            this.DetectionNewFaces = detectionNewFaces;
            this.SetPersonId = setPersonId;
            this.RecognizeTargets = recognizeTargets;
            this.RecognizeParameters = recognizeParameters;
            this.OriginalFilename = originalFilename;
        }
        
        /// <summary>
        /// your API key or d45fd466-51e2-4701-8da8-04351c872236
        /// </summary>
        /// <value>your API key or d45fd466-51e2-4701-8da8-04351c872236</value>
        [DataMember(Name="api_key", EmitDefaultValue=false)]
        public Guid? ApiKey { get; set; }

        /// <summary>
        /// publicly accessible media file uri.
        /// </summary>
        /// <value>publicly accessible media file uri.</value>
        [DataMember(Name="file_uri", EmitDefaultValue=false)]
        public string FileUri { get; set; }

        /// <summary>
        /// base64 encoded media file content. file_uri parameter will be ignored if file_base64 parameter is specified and not empty.
        /// </summary>
        /// <value>base64 encoded media file content. file_uri parameter will be ignored if file_base64 parameter is specified and not empty.</value>
        [DataMember(Name="file_base64", EmitDefaultValue=false)]
        public string FileBase64 { get; set; }

        /// <summary>
        /// (optional) comma separated list of detection flags: bestface - return only face with highest detection score, centerface - same as bestface but gives preference to face closest to image center, basicpoints - 22 basic points detection, propoints - 101 pro points detection, classifiers - face classification and attributes, extended - extended color and geometric measurements, content - image content detection.  for example: \&quot;basicpoints,propoints,classifiers,content\&quot;
        /// </summary>
        /// <value>(optional) comma separated list of detection flags: bestface - return only face with highest detection score, centerface - same as bestface but gives preference to face closest to image center, basicpoints - 22 basic points detection, propoints - 101 pro points detection, classifiers - face classification and attributes, extended - extended color and geometric measurements, content - image content detection.  for example: \&quot;basicpoints,propoints,classifiers,content\&quot;</value>
        [DataMember(Name="detection_flags", EmitDefaultValue=false)]
        public string DetectionFlags { get; set; }

        /// <summary>
        /// (optional) filter faces with detection score lower than min_score.
        /// </summary>
        /// <value>(optional) filter faces with detection score lower than min_score.</value>
        [DataMember(Name="detection_min_score", EmitDefaultValue=false)]
        public double? DetectionMinScore { get; set; }

        /// <summary>
        /// (optional) override automatic faces detection and manually specify faces locations, face points and person ids to assign.  provide an array of new faces
        /// </summary>
        /// <value>(optional) override automatic faces detection and manually specify faces locations, face points and person ids to assign.  provide an array of new faces</value>
        [DataMember(Name="detection_new_faces", EmitDefaultValue=false)]
        public List<NewFace> DetectionNewFaces { get; set; }

        /// <summary>
        /// (optional) set person id in format name@namespace to each detected face. recommended to use with detection_flags bestface, centerface and/or min_score minimum detection score parameter.
        /// </summary>
        /// <value>(optional) set person id in format name@namespace to each detected face. recommended to use with detection_flags bestface, centerface and/or min_score minimum detection score parameter.</value>
        [DataMember(Name="set_person_id", EmitDefaultValue=false)]
        public string SetPersonId { get; set; }

        /// <summary>
        /// (optional) for each detected face run recognize against specified targets (face ids, person ids or namespaces).
        /// </summary>
        /// <value>(optional) for each detected face run recognize against specified targets (face ids, person ids or namespaces).</value>
        [DataMember(Name="recognize_targets", EmitDefaultValue=false)]
        public List<string> RecognizeTargets { get; set; }

        /// <summary>
        /// (optional) comma separated list of recognition parameters, currently supported min_match_score (minimum recognition score), min_score (minimum detection score), gender and race filter.  for example: \&quot;min_match_score:0.4,min_score:0.2,gender:male,race:white\&quot;
        /// </summary>
        /// <value>(optional) comma separated list of recognition parameters, currently supported min_match_score (minimum recognition score), min_score (minimum detection score), gender and race filter.  for example: \&quot;min_match_score:0.4,min_score:0.2,gender:male,race:white\&quot;</value>
        [DataMember(Name="recognize_parameters", EmitDefaultValue=false)]
        public string RecognizeParameters { get; set; }

        /// <summary>
        /// (optional) original media filename, path, uri or your application specific id that you want to be stored in media metadata for reference.
        /// </summary>
        /// <value>(optional) original media filename, path, uri or your application specific id that you want to be stored in media metadata for reference.</value>
        [DataMember(Name="original_filename", EmitDefaultValue=false)]
        public string OriginalFilename { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MediaUpload {\n");
            sb.Append("  ApiKey: ").Append(ApiKey).Append("\n");
            sb.Append("  FileUri: ").Append(FileUri).Append("\n");
            sb.Append("  FileBase64: ").Append(FileBase64).Append("\n");
            sb.Append("  DetectionFlags: ").Append(DetectionFlags).Append("\n");
            sb.Append("  DetectionMinScore: ").Append(DetectionMinScore).Append("\n");
            sb.Append("  DetectionNewFaces: ").Append(DetectionNewFaces).Append("\n");
            sb.Append("  SetPersonId: ").Append(SetPersonId).Append("\n");
            sb.Append("  RecognizeTargets: ").Append(RecognizeTargets).Append("\n");
            sb.Append("  RecognizeParameters: ").Append(RecognizeParameters).Append("\n");
            sb.Append("  OriginalFilename: ").Append(OriginalFilename).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MediaUpload);
        }

        /// <summary>
        /// Returns true if MediaUpload instances are equal
        /// </summary>
        /// <param name="input">Instance of MediaUpload to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MediaUpload input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ApiKey == input.ApiKey ||
                    (this.ApiKey != null &&
                    this.ApiKey.Equals(input.ApiKey))
                ) && 
                (
                    this.FileUri == input.FileUri ||
                    (this.FileUri != null &&
                    this.FileUri.Equals(input.FileUri))
                ) && 
                (
                    this.FileBase64 == input.FileBase64 ||
                    (this.FileBase64 != null &&
                    this.FileBase64.Equals(input.FileBase64))
                ) && 
                (
                    this.DetectionFlags == input.DetectionFlags ||
                    (this.DetectionFlags != null &&
                    this.DetectionFlags.Equals(input.DetectionFlags))
                ) && 
                (
                    this.DetectionMinScore == input.DetectionMinScore ||
                    (this.DetectionMinScore != null &&
                    this.DetectionMinScore.Equals(input.DetectionMinScore))
                ) && 
                (
                    this.DetectionNewFaces == input.DetectionNewFaces ||
                    this.DetectionNewFaces != null &&
                    this.DetectionNewFaces.SequenceEqual(input.DetectionNewFaces)
                ) && 
                (
                    this.SetPersonId == input.SetPersonId ||
                    (this.SetPersonId != null &&
                    this.SetPersonId.Equals(input.SetPersonId))
                ) && 
                (
                    this.RecognizeTargets == input.RecognizeTargets ||
                    this.RecognizeTargets != null &&
                    this.RecognizeTargets.SequenceEqual(input.RecognizeTargets)
                ) && 
                (
                    this.RecognizeParameters == input.RecognizeParameters ||
                    (this.RecognizeParameters != null &&
                    this.RecognizeParameters.Equals(input.RecognizeParameters))
                ) && 
                (
                    this.OriginalFilename == input.OriginalFilename ||
                    (this.OriginalFilename != null &&
                    this.OriginalFilename.Equals(input.OriginalFilename))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ApiKey != null)
                    hashCode = hashCode * 59 + this.ApiKey.GetHashCode();
                if (this.FileUri != null)
                    hashCode = hashCode * 59 + this.FileUri.GetHashCode();
                if (this.FileBase64 != null)
                    hashCode = hashCode * 59 + this.FileBase64.GetHashCode();
                if (this.DetectionFlags != null)
                    hashCode = hashCode * 59 + this.DetectionFlags.GetHashCode();
                if (this.DetectionMinScore != null)
                    hashCode = hashCode * 59 + this.DetectionMinScore.GetHashCode();
                if (this.DetectionNewFaces != null)
                    hashCode = hashCode * 59 + this.DetectionNewFaces.GetHashCode();
                if (this.SetPersonId != null)
                    hashCode = hashCode * 59 + this.SetPersonId.GetHashCode();
                if (this.RecognizeTargets != null)
                    hashCode = hashCode * 59 + this.RecognizeTargets.GetHashCode();
                if (this.RecognizeParameters != null)
                    hashCode = hashCode * 59 + this.RecognizeParameters.GetHashCode();
                if (this.OriginalFilename != null)
                    hashCode = hashCode * 59 + this.OriginalFilename.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
