/* 
 * Betaface API 2.0
 *
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// represents a recognition request for one or more faces.
    /// </summary>
    [DataContract]
    public partial class RecognizeRequest :  IEquatable<RecognizeRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RecognizeRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RecognizeRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RecognizeRequest" /> class.
        /// </summary>
        /// <param name="apiKey">your API key or d45fd466-51e2-4701-8da8-04351c872236 (required).</param>
        /// <param name="facesUuids">list of face unique identifiers that should be recognized. (required).</param>
        /// <param name="targets">list of recognition targets which can include face identifiers, fully qualified person ids in format name@namespace or entire namespaces in format all@namespace. (required).</param>
        /// <param name="parameters">(optional) comma separated list of recognition parameters, currently supported min_match_score (minimum recognition score), min_score (minimum detection score), gender and race filter.  for example: \&quot;min_match_score:0.4,min_score:0.2,gender:male,race:white\&quot;.</param>
        public RecognizeRequest(Guid? apiKey = default(Guid?), List<Guid?> facesUuids = default(List<Guid?>), List<string> targets = default(List<string>), string parameters = default(string))
        {
            // to ensure "apiKey" is required (not null)
            if (apiKey == null)
            {
                throw new InvalidDataException("apiKey is a required property for RecognizeRequest and cannot be null");
            }
            else
            {
                this.ApiKey = apiKey;
            }
            // to ensure "facesUuids" is required (not null)
            if (facesUuids == null)
            {
                throw new InvalidDataException("facesUuids is a required property for RecognizeRequest and cannot be null");
            }
            else
            {
                this.FacesUuids = facesUuids;
            }
            // to ensure "targets" is required (not null)
            if (targets == null)
            {
                throw new InvalidDataException("targets is a required property for RecognizeRequest and cannot be null");
            }
            else
            {
                this.Targets = targets;
            }
            this.Parameters = parameters;
        }
        
        /// <summary>
        /// your API key or d45fd466-51e2-4701-8da8-04351c872236
        /// </summary>
        /// <value>your API key or d45fd466-51e2-4701-8da8-04351c872236</value>
        [DataMember(Name="api_key", EmitDefaultValue=false)]
        public Guid? ApiKey { get; set; }

        /// <summary>
        /// list of face unique identifiers that should be recognized.
        /// </summary>
        /// <value>list of face unique identifiers that should be recognized.</value>
        [DataMember(Name="faces_uuids", EmitDefaultValue=false)]
        public List<Guid?> FacesUuids { get; set; }

        /// <summary>
        /// list of recognition targets which can include face identifiers, fully qualified person ids in format name@namespace or entire namespaces in format all@namespace.
        /// </summary>
        /// <value>list of recognition targets which can include face identifiers, fully qualified person ids in format name@namespace or entire namespaces in format all@namespace.</value>
        [DataMember(Name="targets", EmitDefaultValue=false)]
        public List<string> Targets { get; set; }

        /// <summary>
        /// (optional) comma separated list of recognition parameters, currently supported min_match_score (minimum recognition score), min_score (minimum detection score), gender and race filter.  for example: \&quot;min_match_score:0.4,min_score:0.2,gender:male,race:white\&quot;
        /// </summary>
        /// <value>(optional) comma separated list of recognition parameters, currently supported min_match_score (minimum recognition score), min_score (minimum detection score), gender and race filter.  for example: \&quot;min_match_score:0.4,min_score:0.2,gender:male,race:white\&quot;</value>
        [DataMember(Name="parameters", EmitDefaultValue=false)]
        public string Parameters { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RecognizeRequest {\n");
            sb.Append("  ApiKey: ").Append(ApiKey).Append("\n");
            sb.Append("  FacesUuids: ").Append(FacesUuids).Append("\n");
            sb.Append("  Targets: ").Append(Targets).Append("\n");
            sb.Append("  Parameters: ").Append(Parameters).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RecognizeRequest);
        }

        /// <summary>
        /// Returns true if RecognizeRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of RecognizeRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RecognizeRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ApiKey == input.ApiKey ||
                    (this.ApiKey != null &&
                    this.ApiKey.Equals(input.ApiKey))
                ) && 
                (
                    this.FacesUuids == input.FacesUuids ||
                    this.FacesUuids != null &&
                    this.FacesUuids.SequenceEqual(input.FacesUuids)
                ) && 
                (
                    this.Targets == input.Targets ||
                    this.Targets != null &&
                    this.Targets.SequenceEqual(input.Targets)
                ) && 
                (
                    this.Parameters == input.Parameters ||
                    (this.Parameters != null &&
                    this.Parameters.Equals(input.Parameters))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ApiKey != null)
                    hashCode = hashCode * 59 + this.ApiKey.GetHashCode();
                if (this.FacesUuids != null)
                    hashCode = hashCode * 59 + this.FacesUuids.GetHashCode();
                if (this.Targets != null)
                    hashCode = hashCode * 59 + this.Targets.GetHashCode();
                if (this.Parameters != null)
                    hashCode = hashCode * 59 + this.Parameters.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
