/* 
 * Betaface API 2.0
 *
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// represents a recognition results for one or more faces.
    /// </summary>
    [DataContract]
    public partial class Recognize :  IEquatable<Recognize>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Recognize" /> class.
        /// </summary>
        /// <param name="recognizeUuid">recognize request unique identifier..</param>
        /// <param name="results">collection of recognize results..</param>
        public Recognize(Guid? recognizeUuid = default(Guid?), List<RecognizeResult> results = default(List<RecognizeResult>))
        {
            this.RecognizeUuid = recognizeUuid;
            this.Results = results;
        }
        
        /// <summary>
        /// recognize request unique identifier.
        /// </summary>
        /// <value>recognize request unique identifier.</value>
        [DataMember(Name="recognize_uuid", EmitDefaultValue=false)]
        public Guid? RecognizeUuid { get; set; }

        /// <summary>
        /// collection of recognize results.
        /// </summary>
        /// <value>collection of recognize results.</value>
        [DataMember(Name="results", EmitDefaultValue=false)]
        public List<RecognizeResult> Results { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Recognize {\n");
            sb.Append("  RecognizeUuid: ").Append(RecognizeUuid).Append("\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Recognize);
        }

        /// <summary>
        /// Returns true if Recognize instances are equal
        /// </summary>
        /// <param name="input">Instance of Recognize to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Recognize input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RecognizeUuid == input.RecognizeUuid ||
                    (this.RecognizeUuid != null &&
                    this.RecognizeUuid.Equals(input.RecognizeUuid))
                ) && 
                (
                    this.Results == input.Results ||
                    this.Results != null &&
                    this.Results.SequenceEqual(input.Results)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RecognizeUuid != null)
                    hashCode = hashCode * 59 + this.RecognizeUuid.GetHashCode();
                if (this.Results != null)
                    hashCode = hashCode * 59 + this.Results.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
