/* 
 * Betaface API 2.0
 *
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// represents a recognition results for one or more faces.
    /// </summary>
    [DataContract]
    public partial class Transform :  IEquatable<Transform>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Transform" /> class.
        /// </summary>
        /// <param name="transformUuid">transform request unique identifier..</param>
        /// <param name="imageBase64">base64 encoded transofrm result image file (jpg or png)..</param>
        public Transform(Guid? transformUuid = default(Guid?), string imageBase64 = default(string))
        {
            this.TransformUuid = transformUuid;
            this.ImageBase64 = imageBase64;
        }
        
        /// <summary>
        /// transform request unique identifier.
        /// </summary>
        /// <value>transform request unique identifier.</value>
        [DataMember(Name="transform_uuid", EmitDefaultValue=false)]
        public Guid? TransformUuid { get; set; }

        /// <summary>
        /// base64 encoded transofrm result image file (jpg or png).
        /// </summary>
        /// <value>base64 encoded transofrm result image file (jpg or png).</value>
        [DataMember(Name="image_base64", EmitDefaultValue=false)]
        public string ImageBase64 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Transform {\n");
            sb.Append("  TransformUuid: ").Append(TransformUuid).Append("\n");
            sb.Append("  ImageBase64: ").Append(ImageBase64).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Transform);
        }

        /// <summary>
        /// Returns true if Transform instances are equal
        /// </summary>
        /// <param name="input">Instance of Transform to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Transform input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TransformUuid == input.TransformUuid ||
                    (this.TransformUuid != null &&
                    this.TransformUuid.Equals(input.TransformUuid))
                ) && 
                (
                    this.ImageBase64 == input.ImageBase64 ||
                    (this.ImageBase64 != null &&
                    this.ImageBase64.Equals(input.ImageBase64))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TransformUuid != null)
                    hashCode = hashCode * 59 + this.TransformUuid.GetHashCode();
                if (this.ImageBase64 != null)
                    hashCode = hashCode * 59 + this.ImageBase64.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
